# Generated by Django 5.0.1 on 2024-02-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_addres',
            new_name='shipping_address',
        ),
    ]
