# Generated by Django 5.0.1 on 2024-02-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_shipping_addres_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_addres',
            new_name='street_address',
        ),
    ]
