# Generated by Django 5.0.1 on 2024-02-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_street_addres_shippingaddress_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amout',
            new_name='amount',
        ),
    ]
