# Generated by Django 5.0.1 on 2024-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/products/default.jpg', upload_to='images/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
